name: Build
on:
  push:
  pull_request:
jobs:
  build:
    name: Build on ${{ matrix.os }} with Java ${{ matrix.java }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java: [21]                     # Java LTS; minimum supported by Minecraft
        os: [ubuntu-22.04, windows-2022]  # Supported platforms
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: microsoft
      - name: Make Gradle wrapper executable (Linux/macOS)
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew build --no-daemon
      - name: Upload build artifacts
        if: ${{ runner.os == 'Linux' && matrix.java == '21' }}
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-${{ github.run_number }}
          path: build/libs/
